HT20/my_shop/cart/urls.py
from django.urls import path

from .views import cart_detail, cart_add, cart_remove

urlpatterns = [
    path('cart/', cart_detail, name='cart_detail'),
    path('add/<product_id>/', cart_add, name='cart_add'),
    path('remove/<product_id>/', cart_remove, name='cart_remove'),
]

HT20/my_shop/my_shop/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('ui.urls')),
    path('admin/', admin.site.urls),
    path('products/', include('product.urls')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
]

HT20/my_shop/product/urls.py
from django.urls import path

from .views import product_details, get_new_id, products

app_name = 'products'

urlpatterns = [
    path('', products, name='list'),
    path('<int:pid>/', product_details, name='details'),
    path('new_id/', get_new_id, name='new_id'),
]

HT20/my_shop/ui/urls.py
from django.urls import path

from .views import index


app_name = 'ui'

urlpatterns = [
    path('', index, name='index')
]

HT20/my_shop/cart/models.py
from django.db import models

# Create your models here.

HT20/my_shop/product/models.py
from django.db import models


class Product(models.Model):
    product_id = models.IntegerField(blank=False)
    title = models.CharField(max_length=50, default= 'Default title')
    price= models.DecimalField(max_digits=10, decimal_places=2, default='0,00')
    old_price = models.DecimalField(max_digits=10, decimal_places=2, default='0,00')
    brand = models.CharField(max_length=50, default= 'Default title')
    url= models.CharField(max_length=50, default= 'Default link')
    in_stock = models.BooleanField()


class ScrapingTask(models.Model):
    New_ids = models.TextField(max_length=1000, default="Enter ids here")

    def __str__(self):
        return self.New_ids

HT20/my_shop/ui/models.py
from django.db import models

# Create your models here.

HT20/my_shop/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 50)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

HT20/my_shop/product/forms.py
from django.forms import ModelForm, Textarea
from django import forms

from .models import ScrapingTask


class NewIdsForm(ModelForm):
   class Meta:
      model = ScrapingTask
      fields = ('New_ids',)
      widgets = {'New_ids': Textarea(attrs={'cols': 30, 'rows': 20}),}

HT20/my_shop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from product.views import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    #вигляд для видалення
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

HT20/my_shop/product/views.py
from django.shortcuts import render, get_object_or_404

from .models import Product, ScrapingTask
from .forms import NewIdsForm
from .add_products.rozetka_api import product_params
from cart.forms import CartAddProductForm

def products(request):
    all_products = Product.objects.all()
    return render(request, 'product/product_list.html', context={'all_products': all_products})

def product_details(request, pid):
    product = get_object_or_404(Product, id=pid)
    cart_product_form = CartAddProductForm()
    return render(request, 'product/product_details.html', context={'product': product, 'cart_product_form': cart_product_form})

def get_new_id(request):
    if request.method == "POST":
        form = NewIdsForm(request.POST)
        if form.is_valid():
            form.save()
            bufer = (ScrapingTask.objects.all().last()).New_ids
            new_procucts_id = bufer.split('\n')
            for product_id in new_procucts_id:
                new_product(product_id)
    else:
        form = NewIdsForm()
    return render(request, 'product/add_products.html', context={'form': form})

def new_product(id_product):
    details = product_params(id_product) #'363882639'
    if details:
        if details['in_stock'] == '0':
            active = False
        else:
            active = True
        Product.objects.update_or_create(product_id=details['item_id'],
                                                   defaults={
                                                       'title': details['title'], 'price': details['current_price'],
                                                       'old_price': details['old_price'], 'brand': details['brand'],
                                                       'url': details['href'], 'in_stock': active}
                                                   )

HT20/my_shop/ui/views.py
from django.shortcuts import redirect, reverse


def index(request):
    return redirect(reverse('products:list'))

HT20/my_shop/cart/templates/cart/detail.html
{% extends 'ui/base.html' %}

{% block extra_styles %}
    <style>
    .in-stock {
        background-color: chartreuse;
    }
    .out-of-stock {
        background-color: coral;
    }
    </style>
{% endblock %}

{% block content %}
    <h1>Your shopping cart</h1>
    <table class="cart">
        <thead>
        <tr>
            <th>Product</th>
            <th>Quantity</th>
            <th>View details</th>
            <th> Remove </th>
            <th> Unit price </th>
            <th> Price </th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>{{ product.title}}</td>
                    <td>{{ item.quantity }}</td>
                    <td><a href="{% url 'products:details' product.id %}">Details</a></td>
                    <td><a href="{% url "cart:cart_remove" product.id%}">Remove</a></td>
                    <td class="num">{{ item.price }} grn </td>
                    <td class="num">{{ item.total_price }} grn </td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total quantity">
            <td>Total quantity</td>
            <td class="num">{{cart.get_total_quantity}}</td>
        </tr>
        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">{{ cart.get_total_price }} grn </td>
        </tr>
        </tbody>
    </table>
    <p class="text-light">
        <a href="{% url "products:list" %}" class="button light">Continue shopping</a>
    </p>
{% endblock %}

HT20/my_shop/product/templates/product/add_products.html
{% extends 'ui/base.html' %}

<p>Enter the comma-separated ID that you want to add to your products.</p>

{% block content %}

    <p>Enter  IDs that you want to add to your products,  each ID on a new line.</p>
<form action="" method="post" novalidate>
{% csrf_token %}
{{ form }}
<input type="submit" value="Send">
</form>
{% endblock %}

HT20/my_shop/product/templates/product/product_details.html
{% extends 'ui/base.html' %}

{% block extra_styles %}
    <style>
    .in-stock {
        background-color: chartreuse;
    }
    .out-of-stock {
        background-color: coral;
    }
    </style>
{% endblock %}

{% block content %}
    <h3>Product details</h3>

    <div>
        <hr>
        <p> Title: {{ product.title }}</p>
        <p> ID: {{ product.product_id }}</p>
        <p> Price: {{ product.price }}</p>
        <p> Old price: {{ product.old_price }}</p>
        <p> Brand : {{ product.brand  }}</p>
        <p> In Stock: <span class="{% if product.in_stock %}in-stock{% else %}out-of-stock{% endif %} ">{{  product.in_stock|yesno:'In Stock, Out Of Stock' }} </span></p>
        <p> View on external site: <a href="{{ product.url }}" target="_blank">View....</a></p>
        <form action="{% url "cart:cart_add" product.id %}" method="post">
            {{ cart_product_form }}
            {% csrf_token %}
            <input type="submit" value="Add to cart">
        </form>
        <hr>
    </div>

{% endblock %}

HT20/my_shop/product/templates/product/product_list.html
{% extends 'ui/base.html' %}

{% block extra_styles %}
    <style>
    .in-stock {
        background-color: chartreuse;
    }
    .out-of-stock {
        background-color: coral;
    }
    </style>
{% endblock %}

{% block content %}
    <div>
    <h2>My product</h2>
    {% for product in all_products %}
        <div>
            <p> Title: {{ product.title }}</p>
            <p> Price: {{ product.price }}</p>
            <p> In Stock: <span class="{% if product.in_stock %}in-stock{% else %}out-of-stock{% endif %} ">{{  product.in_stock|yesno:'In Stock, Out Of Stock' }} </span></p>
            <p> View details: <a href="{% url 'products:details' product.id %}" target="_blank">View....</a></p>
        </div>
    </div>
    {% endfor %}

{% endblock %}

HT20/my_shop/ui/templates/ui/base.html
<!DOCTYPE html>
<html lang="en">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial - scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>MY rozetka Shop</title>
    <style>
        #nav-header > li {
            display: inline-block;
            min-width: 100px;
            padding: 10px 5px 10px 5px;
        }
        .active-nav {
            border: blueviolet 5px;
        }
    </style>
</head>
<body>
{# Naviigation Header #}
<h2>My rozetka Shop</h2>
<div>
    <ul id="nav-header">
        <li {% if request.resolver_match.view_name == 'ui:index' %}class="active-nav"{% endif %}><a href="{% url 'ui:index' %}">Index </a></li>
        <li {% if request.resolver_match.view_name == 'products:list' %}class="active-nav"{% endif %}><a href="{% url 'products:list' %}">Products </a></li>
        <li {% if request.resolver_match.view_name == 'form:form' %}class="active-nav"{% endif %}><a href="{% url 'products:new_id' %}">Add products </a></li>
        <li {% if request.resolver_match.view_name == 'cart:cart_detail' %}class="active-nav"{% endif %}><a href="{% url 'cart:cart_detail' %}">Cart </a></li>
    </ul>
</div>
{# Content #}
{% block content %}
{% endblock %}
</body>
</html>

HT20/my_shop/ui/templates/ui/index.html
{% extends 'ui/base.html' %}

{% block content %}
    <h3>Hello!!!</h3>


    <div>

    </div>
{% endblock %}